### ISSUE TITLE
Bug when paging through images in media library

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3817] opened 2021-07-16 12:33 UTC
# Problem
When adding an image through WYSIWYG, if you search by a string and then remove the search string and try to page through the image library, the search string gets applied after paging.

# Steps to reproduce
Click to add media in WYSIWYG
Enter a string to search images in media library and click apply filters
Remove search string and click apply filters
click to navigate to the next page of images in the library
the library is filtered again by the previous search string.

# Proposed solution
- [ ] Look through media library issue queue for possible fixes as we are not doing any thing custom here.

**Comment by joewhitsitt** [comment] 2023-12-12 21:07
I can't reproduce this on sandbox.prod. Looking for one more to confirm before closing.

**Comment by briand44** [comment] 2023-12-12 21:37
I can't reproduce either.

**Closed as not planned** 2023-12-12 21:38 UTC
Labels: bug, bug-smash-prioritized
