### ISSUE TITLE
Breadcrumbs not showing for view pages

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1037] opened 2020-02-11 20:17 UTC
This may be a problem that exists for more entities, but for now, this is where I am seeing the issue. I have a view page created on the icsa.uiowa.edu site at https://icsa.uiowa.edu/projects that is not using LB but it does not show the breadcrumbs.

![Screen Shot 2020-02-11 at 2 17 28 PM](https://user-images.githubusercontent.com/3067017/74275302-41932d00-4cd9-11ea-8a4b-524c55b37940.png)

**Comment by pyrello** [comment] 2020-02-19 20:16
In looking at this, I don't see that you have the plugin enabled for the Breadcrumbs block that changes its visibility based on Layout Builder. I haven't had a chance to use xdebug to see if it is somehow checking that condition, but this seems like maybe its not a bug with the Layout Builder Custom module.

**Comment by joewhitsitt** [comment] 2020-03-27 15:01
@pyrello did this git fixed for all view pages rendered with uids_base or just uiowa.edu? https://github.com/uiowa/uiowa/pull/1260

**Comment by pyrello** [comment] 2020-03-27 15:13
I believe this should be fixed for all non-node pages rendered via uids_base. However, the site above is using the collegiate_theme, so this would not affect that.

@mark-bennett-uiowa The easiest and quickest way to fix this without having to immediately migrate the site off of the Collegiate profile would be to add a breadcrumb region to collegiate_theme. That turned out to be the reason this was not rendering is because there was no region output in the page template there.

Just copy from uids_base: https://github.com/uiowa/uiowa/blob/6341420469bc9e5989d93a7525ad4d093209bfdc/docroot/themes/custom/uids_base/templates/layout/page.html.twig#L94-L96

**Comment by joewhitsitt** [comment] 2020-05-13 17:45
@mark-bennett-uiowa Is this still an issue if icsa is moving to the sitenow profile?

**Comment by richardbporter** [comment] 2020-05-21 15:49
Seems to be displaying now on https://icsa.uiowa.edu/projects. Going to close this but please reopen if still an issue.

**Closed as completed by richardbporter** 2020-05-21 15:49 UTC
Labels: bug
