### ISSUE TITLE
Regression with search bar + vertical toolbar

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1253] opened 2020-03-24 21:39 UTC
<img width="1669" alt="Screen Shot 2020-03-24 at 4 34 21 PM" src="https://user-images.githubusercontent.com/709009/77479614-20505100-6dee-11ea-9d8d-77b2d6fd81fb.png">

Regression introduced in #1236.

# Proposed solution

Create a new `iowa-bar-admin` partial file for `admin.scss` targeting `.toolbar-vertical.toolbar-tray-open` to adjust the styles to work with the vertical toolbar.

**Comment by bspeare** [comment] 2020-05-12 14:15
Related regression for tertiary option:

<img width="1524" alt="screen_shot_2020-05-12_at_8 59 04_am" src="https://user-images.githubusercontent.com/1036433/81702603-213a5200-9431-11ea-8884-dbe4e3a25bef.png">

**Comment by bspeare** [comment] 2021-09-14 19:10
The top links were introduced since this issue was created will also need to be fixed with this work:

<img width="1616" alt="Screen Shot 2021-09-14 at 2 08 56 PM" src="https://user-images.githubusercontent.com/1036433/133319236-fd686cf2-896b-4d88-8d79-08b03014036a.png">

**Closed as completed** 2023-07-28 22:07 UTC
Labels: bug, uids_base, uiowa.edu, bug-smash-prioritized
