### ISSUE TITLE
Upgrade to Drupal 9.3.x

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4562] opened 2021-12-13 21:34 UTC
# Motivation
Drupal 9.3.0 is out: https://www.drupal.org/project/drupal/releases/9.3.0

# Proposed solution

- [ ] Upgrade to Drupal 9.3.x
- [ ] Review the changes at the link above and figure out what is going to need to change and add it here
- [ ] Other stuff

**Comment by pyrello** [comment] 2021-12-14 18:12
There is a known issue for 9.3.0 that may affect our platform: https://www.drupal.org/project/drupal/issues/3253568

Based on that, it might make sense to wait for 9.3.1 as it is likely to be released soon to fix that bug.

**Comment by richardbporter** [comment] 2021-12-15 15:59
This seems like a duplicate of https://github.com/uiowa/uiowa/issues/4411.

**Closed as completed** 2021-12-16 15:19 UTC
Labels: dependencies
