### ISSUE TITLE
Admissions - Webmaster content permissions don't appear to match what is available

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3381] opened 2021-04-18 22:15 UTC
# Problem

In attempting to look into #3380, I noticed something weird. Looking at Webmaster role permissions, it would seem that they shouldn't even be able to create an Area of Study item. However when I masquerade as someone with the Webmaster role, I can see the link to add an Area of Study. I did not see the same behavior for an Editor.

Really not sure what is going on here, but I'm pretty sure something weird is going on.

# Steps to reproduce
* Visit https://admissions.prod.drupal.uiowa.edu/admin/people/permissions and view the Node permissions.
  ![Screen Shot 2021-04-18 at 5 14 55 PM](https://user-images.githubusercontent.com/709009/115162525-9e227280-a069-11eb-9b37-51ae8d482956.png)
* Masquerade as a webmaster.
* Visit https://admissions.prod.drupal.uiowa.edu/node/add and note that Area of Study shows up.
  ![Screen Shot 2021-04-18 at 5 13 51 PM](https://user-images.githubusercontent.com/709009/115162503-77643c00-a069-11eb-90bf-45aaffd970d8.png)

# Proposed solution
TBD

**Comment by joewhitsitt** [comment] 2021-04-26 22:25
<img width="1036" alt="Screen Shot 2021-04-26 at 5 20 36 PM" src="https://user-images.githubusercontent.com/4663676/116158183-d5210580-a6b3-11eb-9e27-297452352ce7.png">

Looks like we are allow webmasters to work with all node content within the default config. https://github.com/uiowa/uiowa/issues/1355

**Comment by pyrello** [comment] 2021-04-27 12:52
Ah ha! Thanks, @joewhitsitt. I thought I was going a little crazy. I think this is probably resolved then.

**Comment by joewhitsitt** [comment] 2021-04-27 13:57
Closing. "Works as designed"

**Closed as completed by joewhitsitt** 2021-04-27 13:57 UTC
Labels: bug
