### ISSUE TITLE
Audit Layout Builder Off-Canvas Styles

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3401] opened 2021-04-22 16:33 UTC
# Problem

[With 9.1.7](https://github.com/uiowa/uiowa/pull/3397), a patch we had been using no longer applied that the merged solution differed greatly from what we were doing. This has resulted in regressions to our layout builder settings tray styles. Some of which were temporarily fixed in order to move forward with the security release.

# Proposed solution

- With the new reset, we should audit our overrides to make sure they are still doing what we want them to do. Make adjustments, remove styles that are no longer needed.
- Look for ways to consolidate and organize so that these can be found easier in the future.

**Comment by cory-skeers** [comment] 2021-05-07 17:12
Checked through the collections and slider forms as part of #3479 bug fix, and the dropdown-toggle/remove bug looks to be the only issue there.

There's still a possibility of cleanup and consolidation, but the overall updates to fix the bug were fairly light.

Other block forms could still use auditing.

**Comment by bspeare** [comment] 2021-06-28 20:49
Do we want to include spacing/line-height fixes in this audit to fix issues like the screenshot below?  The issue could be from the lack of previous styles being applied. 

<img width="369" alt="Screen Shot 2021-06-28 at 3 11 03 PM" src="https://user-images.githubusercontent.com/1036433/123702034-400fc980-d828-11eb-8469-6b2153b943c3.png">

`background: inherit` is causing the issue from `core/themes/stable/css/core/dialog/off-canvas.base.css`

**Comment by makurj** [comment] 2021-06-28 21:04
I would like to pair on this.

**Comment by bspeare** [comment] 2021-08-24 15:50
Another thing we might want to do during this audit is split `admin.scss` into partials so we have better clarity and make editing those styles easier.

**Comment by bspeare** [comment] 2021-09-21 19:30
We could also skip this work and just move to https://www.drupal.org/project/gin which now has 10,000 sites using it.   Perhaps we could talk https://github.com/uiowa/uiowa/pull/3370 at our next Drupal meeting.

**Comment by pyrello** [comment] 2021-09-28 15:13
I agree with @bspeare that we should consider moving to Gin instead of this. It may be the case that we still have to fix some of this stuff, but overall we may have to fix less.

**Comment by briand44** [comment] 2021-09-28 18:55
postponed until we discuss https://github.com/uiowa/uiowa/issues/4204

**Comment by bspeare** [comment] 2022-06-14 19:19
We did refactor the admin styles into partials for better code organization in https://github.com/uiowa/uiowa/pull/4211/files.

**Comment by bspeare** [comment] 2022-06-15 16:03
We also fixed the details/summary toggles in the horizontal menu pr and added https://github.com/uiowa/uiowa/blob/349db34434cae24b7dcf4ab8ec03522174f6e662/docroot/themes/custom/uids_base/scss/admin/_off-canvas.scss#L124-L130.

**Comment by bspeare** [comment] 2022-06-15 16:09
The line-height issue in https://github.com/uiowa/uiowa/issues/3401#issuecomment-870031333 was also fixed in https://github.com/uiowa/uiowa/pull/3926.

**Comment by bspeare** [comment] 2022-06-15 16:13
I think a lot of the problems that we were seeing may no longer be an issue after we have slowly made improvements on this over the past year.    The remaining work to do on this would be to possibly find one place to put the off-canvas styles.  

We are currently placing them in two spots:

- https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/css/layout_builder_custom.overrides.css
- https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/admin/_off-canvas.scss

If we still think this is a priority, let's document any remaining "regressions to our layout builder settings tray styles" since I'm not sure a general audit will be that helpful at this point.

**Comment by pyrello** [comment] 2022-06-16 17:31
Should we adapt this issue to be more specific to the issues that we know we still want to fix? Or create a new issue to document the changes suggested above and then let future issues bubble up and close this one?

**Comment by joewhitsitt** [comment] 2023-12-12 20:16
I feel like we took an unintentional dive into this with our D10 upgrade. Should we leave this open or close it?

**Comment by bspeare** [comment] 2023-12-12 20:19
Please close it.

**Closed as completed** 2023-12-12 20:33 UTC
Labels: bug, postponed, layout builder, bug-smash-prioritized
