### ISSUE TITLE
As a developer writing a migration, I can connect to a PHP 7.4-enabled source from my local.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3938] opened 2021-08-10 18:40 UTC
Related to #3675 

- [x] Investigate connecting DD to Cloud IDE for migrations. Spin up a Cloud IDE with PHP 7.4. Determine what the DB credentials are. Try plugging them into a local site which has sitenow_migrate enabled.

- [x] Investigate getting PHP 7.4 working with DD. https://evolvingweb.ca/blog/install-specific-version-php-or-drush-acquia-dev-desktop Try a typical sitenow_migrate connection.

**Comment by joewhitsitt** [comment] 2021-08-13 13:13
starting with no. 2 until a more appropriate mobbing hour when i can fumble through cloud ide with others.

**Comment by richardbporter** [comment] 2021-08-13 13:29
I think it may be necessary for everyone to install PHP 7.4 locally to get DrupalVM dependencies installed for Drupal 9, right?

**Comment by joewhitsitt** [comment] 2021-08-13 13:32
probs. i've had 7.4.15 since i got the new computer. working session participants should also have 7.4

**Comment by joewhitsitt** [comment] 2021-08-13 13:34
evolvingweb instructions are a bit different now since brew changed how php is packaged and devdesktop 64bit. so far so good though. trying to keep track of the diff.

**Comment by joewhitsitt** [comment] 2021-08-13 15:53
## Update DevDesktop to use PHP 7.4 and Drush 8.4.8

_Updated instructions from https://evolvingweb.ca/blog/install-specific-version-php-or-drush-acquia-dev-desktop_

- `brew install php@7.4`
- Take note of actual version of 7.4 is installed.
- `cp -r /usr/local/Cellar/php@7.4/7.4.15 /Applications/DevDesktop/php7_4_x64` _change 7.4.15 to the version of php that was installed_
- `cp /usr/local/etc/php/7.4/php.ini /Applications/DevDesktop/php7_4_x64/bin/php.ini`
- In finder go to /Applications/DevDesktop/ and right click on Acquia Dev Desktop to show package contents. Continue to navigate to Contents/MacOS/ and edit `static.ini`
- After the [php/7] block add:

```
[php/8]
id=php7_4
executablePath=php7_4_x64/bin/php
cgiExecutablePath=php7_4_x64/bin/php-cgi
configPath=/Applications/DevDesktop/php7_4_x64/bin/php.ini
```

>Open the ADD Preferences and select the Config tab. Now, in the Default PHP Version, select the one we just added. Make sure you select PHP mode Fast CGI and have PHP use the php.ini we previously copied into ADD in Step 2. Back in the ADD Preferences main window, in the left panel select the site you are working on, and then in Default PHP Version select the desired version. Then, click Ok and restart Apache.

- Edit /Applications/DevDesktop/tools/drush from
```
[ -z "$PHP_ID" ] && PHP_ID=php7_2
PHP_PATH_ENDING="_x64/bin/php"
```
to
```
export PHP_ID="php7_4"
# [ -z "$PHP_ID" ] && PHP_ID=php7_2
PHP_PATH_ENDING="_x64/bin/php"
```

- Edit /Applications/DevDesktop/tools/composer.json and change drush version:

`"drush/drush": "8.4.8",`

- In /Applications/DevDesktop/tools

`composer update --optimize-autoloader`

When you open a dev desktop terminal now, you should get the correct versions with `php -v` `drush version` (maybe some new warnings...). You should also be able to sync a site and see your new php version listed in the /admin/reports/status section of the site.

**Comment by joewhitsitt** [comment] 2021-08-13 20:10
There seem to be several barriers to get CloudIDE working to be a host for migrations. Each IDE is tied to an Acquia user which needs to be destroyed and recreated. The IDE is slow to spin up and requires manual configuration to get going.

Ultimately, the db credentials needed for migration are not needed. Rick mentioned possibly creating an SSH tunnel for this but is further work that might not be worth doing if DD is still viable on 7.4

**Comment by dnkemper** [comment] 2021-08-13 21:00
> ## Update DevDesktop to use PHP 7.4 and Drush 8.4.8
> _Updated instructions from https://evolvingweb.ca/blog/install-specific-version-php-or-drush-acquia-dev-desktop_
> 
> * `brew install php@7.4`
> * Take note of actual version of 7.4 is installed.
> * `cp -r /usr/local/Cellar/php@7.4/7.4.15 /Applications/DevDesktop/php7_4_x64` _change 7.4.15 to the version of php that was installed_
> * `cp /usr/local/etc/php/7.4/php.ini /Applications/DevDesktop/php7_4_x64/bin/php.ini`
> * In finder go to /Applications/DevDesktop/ and right click on Acquia Dev Desktop to show package contents. Continue to navigate to Contents/MacOS/ and edit `static.ini`
> * After the [php/7] block add:
> 
> ```
> [php/8]
> id=php7_4
> executablePath=php7_4_x64/bin/php
> cgiExecutablePath=php7_4_x64/bin/php-cgi
> configPath=/Applications/DevDesktop/php7_4_x64/bin/php.ini
> ```
> 
> > Open the ADD Preferences and select the Config tab. Now, in the Default PHP Version, select the one we just added. Make sure you select PHP mode Fast CGI and have PHP use the php.ini we previously copied into ADD in Step 2. Back in the ADD Preferences main window, in the left panel select the site you are working on, and then in Default PHP Version select the desired version. Then, click Ok and restart Apache.
> 
> * Edit /Applications/DevDesktop/tools/drush from
> 
> ```
> [ -z "$PHP_ID" ] && PHP_ID=php7_2
> PHP_PATH_ENDING="_x64/bin/php"
> ```
> 
> to
> 
> ```
> export PHP_ID="php7_4"
> # [ -z "$PHP_ID" ] && PHP_ID=php7_2
> PHP_PATH_ENDING="_x64/bin/php"
> ```
> 
> * Edit /Applications/DevDesktop/tools/composer.json and change drush version:
> 
> `"drush/drush": "8.4.8",`
> 
> * In /Applications/DevDesktop/tools
> 
> `composer update --optimize-autoloader`
> 
> When you open a dev desktop terminal now, you should get the correct versions with `php -v` `drush version` (maybe some new warnings...). You should also be able to sync a site and see your new php version listed in the /admin/reports/status section of the site.

Tested and everything works accordingly - can keep checking out sites to make sure but nice job!

**Comment by joewhitsitt** [comment] 2021-08-13 21:13
Thanks for reproducing the DD solution @dnkemper. I have moved these instructions to the wiki. Closing.

https://wiki.uiowa.edu/display/sitenow/Update+DevDesktop+to+use+PHP+7.4

**Closed as completed by joewhitsitt** 2021-08-13 21:13 UTC
Labels: story, DX

**Comment by richardbporter** [comment] 2021-08-17 13:52
I'm going to give this a shot but may change the Drush setup if we can use a site-local version that resolves all those warnings.
