### ISSUE TITLE
Figure out the webform.webform.contact/config_ignore issue..

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1552] opened 2020-05-07 19:23 UTC
## Problem
Deployment was plagued with issues, one of which was a config_ignore/missing config (renamed or deleted webform)

```
[error]  TypeError: Argument 2 passed to Drupal\Core\Config\DatabaseStorage::write() must be of the type array, boolean given, called in /mnt/www/html/uiowa/docroot/core/lib/Drupal/Core/Config/StorageCopyTrait.php on line 33 in Drupal\Core\Config\DatabaseStorage->write() (line 120 of /mnt/www/html/uiowa/docroot/core/lib/Drupal/Core/Config/DatabaseStorage.php) #0 /mnt/www/html/uiowa/docroot/core/lib/Drupal/Core/Config/StorageCopyTrait.php(33): Drupal\Core\Config\DatabaseStorage->write('webform.webform...', false)
```

Had to recreate the contact form on the following sites to get a successful deployment:

- nightatthesciencelabs.conference.uiowa.edu
- iniworkshop.conference.uiowa.edu
- molcellcog.org
- pinyin.uiowa.edu
- uibio.org.uiowa.edu

**Comment by richardbporter** [comment] 2020-05-07 20:53
Could be related to the 8.8.5 update. Maybe we try the 3.x dev version of config_ignore first. Otherwise, could this be created through default content?

**Comment by joewhitsitt** [comment] 2020-05-08 13:50
https://www.drupal.org/project/drupal/issues/2925297 (i think the issue is scoped to config_translation, but I saw a comment about webform as well).

I don't think default_content covers webforms as I don't think they are entity based. We could probably programmatically create a webform as part of a provision process (check if already exists first). I think it is valuable to have a example webform for folks.

**Comment by richardbporter** [comment] 2020-05-08 15:02
The 3.x dev version of config_ignore does not seem to respect the `webform.webform.*` rule. :(

**Comment by richardbporter** [comment] 2020-05-08 15:24
The patch in https://www.drupal.org/project/drupal/issues/3100712 works but what are the chances it gets committed? It was linked from a config_ignore issue: https://www.drupal.org/project/config_ignore/issues/3103674

The result is a warning but with a 0 exit code (what we want).
```
vagrant@local:/var/www/uiowa$ drush @sitenowdemo.local cim
 [notice] Missing required data for configuration: webform.webform.contact
 [notice] There are no changes to import.
```

Stupid question but is it possible to turn off translation for this webform or all? If that is even the cause.

**Comment by joewhitsitt** [comment] 2020-05-08 15:30
IMO, since there is nothing stopping sites from deleting these and I at least see the value of a default form, I would like to see a band-aid fix. We can keep this issue open and follow-up as a better solution comes along.

**Comment by richardbporter** [comment] 2020-05-08 17:16
I'll patch it. This is a good summary: https://www.drupal.org/project/drupal/issues/3100712#comment-13525052 I'm sure this won't be the last instance of it with our setup. I don't think it has anything to do with translation. We should invest in seeing the patch through to completion.

**Closed as completed** 2020-05-08 17:47 UTC
Labels: bug

**Comment by joewhitsitt** [comment] 2020-05-08 21:26
@richardbporter if this is working should i remove those webforms i created from those sites?
