### ISSUE TITLE
Site installs - Missing required data for configuration?

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4729] opened 2022-02-01 16:57 UTC
# Problem

```
 [notice] Missing required data for configuration: purge.logger_channels
 [notice] Missing required data for configuration: purge.plugins
 [notice] Missing required data for configuration: sitenow_events.settings
```

# Steps to reproduce
This is showing during site installs after our usual block content and moderation messages.

# Proposed solution
?

**Comment by joewhitsitt** [comment] 2022-02-01 18:27
Related? https://www.drupal.org/project/config_ignore/issues/3168888

**Comment by richardbporter** [comment] 2022-02-02 14:10
Can we close this as a dupe of #1914 ?

**Closed as completed** 2022-02-02 14:37 UTC
Labels: bug
