### ISSUE TITLE
Bug: Update Block button only visible after adjusting browser window size, configure menu size 

### ISSUE THREAD

**Issue by ABoston88** [uiowa/uiowa#4138] opened 2021-09-17 15:13 UTC
From Mallory Valentine at RecServ

So it appears that it does not matter the size of the browser.  Essentially when go to the layout tab and attempt to make an edit to a previously established content, the “update” button is not available – I cannot scroll past Background and the drop down menu.  The minute I adjust the size of the browser (either larger or smaller), the update button will come into view, sometimes not the entire button but enough to where I can select it.  OR if I pull the drag option on the black configure box to make it larger or smaller, it too will appear then.

Browser: Chrome

**Comment by bspeare** [comment] 2021-09-20 13:35
Tested this locally on Browserstack and I was able to recreate.  Most likely being caused by https://github.com/uiowa/uiowa/pull/1965/files.    After removing those files, the issue with the update button was resolved.

**Comment by richardbporter** [comment] 2021-09-27 12:55
Is this happening in a specific version of Chrome?

**Comment by bspeare** [comment] 2021-09-27 13:20
I didn't run through all the versions.   I tried the latest version of Chrome (93) for Windows on Browserstack.

**Comment by richardbporter** [comment] 2021-09-27 18:10
OIC. The drawer is like cut off. Seems like Windows only. Also happening on Edge/FF on Windows 10.

**Comment by richardbporter** [comment] 2021-09-28 13:53
Having trouble narrowing this down.

**Comment by bspeare** [comment] 2021-09-28 15:50
I can confirm that switching to the Gin theme makes the "Update" button visible.

**Comment by bspeare** [comment] 2021-09-28 17:53
I've got a fix for this that I will push up later this afternoon.

**Closed as completed** 2021-09-29 13:18 UTC
Labels: bug, bug-smash-prioritized
