### ISSUE TITLE
Vertical video text is overlapping when wrapped

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1270] opened 2020-03-26 20:27 UTC
<img width="1320" alt="Screen Shot 2020-03-26 at 3 25 56 PM" src="https://user-images.githubusercontent.com/709009/77693350-2ffaa180-6f76-11ea-845b-15efd2aa672d.png">

**Comment by pyrello** [comment] 2020-03-26 20:27
FYI @bspeare

**Comment by bspeare** [comment] 2020-03-26 20:35
This is a duplicate of https://github.com/uiowa/uiowa/issues/1227.   Both use the same component.

**Closed as completed** 2020-03-26 20:39 UTC
Labels: theming, uids_base
