### ISSUE TITLE
New tables PR causing CSS issue with borders and table text

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2256] opened 2020-09-28 23:44 UTC
After the new responsive table PR went into place, I noticed a few issues with styling. The first has to do with borders. I originally had no styling on the tables except for borders=1 placed in the table directly (source). After the PR was merged, this happened:
<img width="1376" alt="Screen Shot 2020-09-28 at 6 09 04 PM" src="https://user-images.githubusercontent.com/3067017/94496287-8e206f80-01b9-11eb-8f82-73c0c0e6d75d.png">

I have since removed all instances of the border=1 and replaced with the class="is-striped" to fix this. Was there any thought to allowing borders on all cells in a table?

The second has to do with text within the td tags also within another html tag (p,ul,ol, etc). The text loses the new smaller text styling within the table. I was able to avoid this using a span tag, but that doesn't work with ul or ol tags. Also notice the bottom alignment of the text in the tall right column cell. This screenshot comes from [https://latinxstudies.prod.drupal.uiowa.edu/undergraduate/minor-latinx-studies](https://latinxstudies.prod.drupal.uiowa.edu/undergraduate/minor-latinx-studies):
<img width="1336" alt="Screen Shot 2020-09-28 at 6 40 11 PM" src="https://user-images.githubusercontent.com/3067017/94496551-5239da00-01ba-11eb-83a3-49e7eccfd85e.png">

**Comment by joewhitsitt** [comment] 2020-12-31 17:52
The issue related to borders was also raised by Todd. I have a PR open here to have a better fallback for folks that had a table border attribute: https://github.com/uiowa/uids/pull/442

**Comment by joewhitsitt** [comment] 2021-05-05 19:00
@mark-bennett-uiowa with the recent table adjustments, is this still an issue?

**Comment by pyrello** [comment] 2021-05-19 13:37
@mark-bennett-uiowa Nudge about whether this is still an issue. I don't think this should be labeled a bug since it was working as intended.

There is a `table--gray-borders` class available for adding borders: https://sitenow.uiowa.edu/documentation/wysiwyg

**Comment by bspeare** [comment] 2021-06-22 13:53
@mark-bennett-uiowa can we close this issue?

**Comment by pyrello** [comment] 2021-06-22 15:06
We believe this may be fixed based on previous work on tables. @mark-bennett-uiowa If this is still an issue, please re-open.

**Closed as completed by pyrello** 2021-06-22 15:06 UTC
Labels: theming

**Comment by mark-bennett-uiowa** [comment] 2021-06-22 15:29
@bspeare @pyrello @joewhitsitt Yes, this appears to be fixed. I ended up removing the bullet list from that page while it was an issue. I just re-added it and it looks like it is working. Thanks all for taking care of this.

![Screen Shot 2021-06-22 at 10 29 25 AM](https://user-images.githubusercontent.com/3067017/122954070-be5dfe80-d344-11eb-8149-cc5223b73ccc.png)
