### ISSUE TITLE
Refactor HawkAlerts implementation for maintainability and utility

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1279] opened 2020-03-27 00:55 UTC
Parent: #1275

**Comment by mjoneill** [comment] 2020-03-27 00:58
This task needs some clarification to clarify the goal for refactoring.  It sounded like it was generally to make sure it was able to be used for future sites and not just a one-off, but I don't have a grasp of the details, nor do I recall the conversation. Can someone clarify this task? 
@joewhitsitt @pyrello @richardbporter

**Comment by pyrello** [comment] 2020-03-27 03:26
This is the task that I had previously created for this: #1271

**Comment by richardbporter** [comment] 2020-03-31 13:37
My thoughts on MVP refactor:

- Module configuration should allow for turning Hawk Alerts on or off but not set the source of the feed.
- The no alert message should be changed to a notice that users can set manually. I don't see a use case for a message to display when there are no alerts.
- Hawk Alerts should have an alert style (red).
- The manual message should have a notice style (yellow).

**Comment by pyrello** [comment] 2020-03-31 13:49
I'm not sure which of the tasks for this story this should show up under, but the other consideration is how to not have a block show unless there is an alert or a message. Right now there is an issue that is caused by the fact that the block always renders, which causes the region to always render. 

Maybe this can be fixed via CSS?

A couple other thoughts/considerations:
* The Alerts region + any block in that region is essentially the same thing as setting a message. Because of the styling of the region, anything placed there will look like an alert.
* I like the idea of allowing the feed source setting to be changed via settings config. That is, the source config is still present and set to production by default. The user can no longer set it via the admin UI, but developers can change it via settings.php for testing. This was your suggestion the other day.

**Comment by mjoneill** [comment] 2020-03-31 13:55
> * Hawk Alerts should have an alert style (red).
> * The manual message should have a notice style (yellow).

Some additional thinking on this: There could be local, manually created alert messages that need to red background. Example: Flood at Tippie.  Danger to health and safety, but the message on the ecomms site (and likely the feed) did not provide enough explanation/context/nor did it have a backlink to the right destination where breaking information was curated, etc.  Sometimes local colleges will have the need to write their own version of an alert that also might be otherwise available in the feed.

**Comment by pyrello** [comment] 2020-03-31 13:59
> Danger to health and safety, but the message on the ecomms site (and likely the feed) did not provide enough explanation/context/nor did it have a backlink to the right destination where breaking information was curated, etc. Sometimes local colleges will have the need to write their own version of an alert that also might be otherwise available in the feed.

@mjoneill In that case, would the site owner need the local message to display in place of the original hawk alert?

**Comment by bspeare** [comment] 2020-03-31 13:59
I'll fix the CSS issue with the region rendering.   I will also put together some variations to look at in our design meeting tomorrow.

**Comment by richardbporter** [comment] 2020-03-31 14:00
The styled div could be rendered via JS instead of printing it all the time when empty. 

I think the MVP for this should allow for one local alert textarea - just swap the no message for that. Anything beyond that could be customized for the site in question. Most likely, folks that need more advanced local alerts will want to integrate them with additional content types/taxonomies like services.

**Comment by bspeare** [comment] 2020-03-31 14:03
Is there a list of alert levels that we can target?  I see the test version has `alert-danger` as a class.  What are the other levels?

**Comment by mjoneill** [comment] 2020-03-31 14:04
> @mjoneill In that case, would the site owner need the local message to display in place of the original hawk alert?

@pyrello Yeah, I think so.  I think it's a binary thing...  Either it's displaying the feed, or it's displaying a local, customized alert message.  

^^ Perfectly willing to account accommodate other use cases and perspectives.  Just trying to reflect on the last time we needed to use this functionality.

**Comment by pyrello** [comment] 2020-04-03 14:31
I think this task is captured in the other tasks in the #1275 story.

**Closed as completed by pyrello** 2020-04-03 14:31 UTC
Labels: uiowa.edu
