### ISSUE TITLE
Deprovision https://clas.uiowa.edu/history/ from CLAS application

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#7070] opened 2023-11-01 15:27 UTC
Replacement history.uiowa.edu launched on 11/1/23. 

From Mike C.:
> We’re OK with removing the old site and no backup is needed.

**Comment by briand44** [comment] 2023-11-01 21:35
This is done. We may need to implement an htaccess redirect yet but waiting on confirmation. Closing this as the issue is to deprovision, which is done.

**Closed as completed by briand44** 2023-11-01 21:35 UTC
Labels: deprovision, Just do it
