### ISSUE TITLE
Artwork mockup for full node and teaser

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7042] opened 2023-10-24 19:30 UTC
# Story

As a web team, we would like to put together some mockups of an artwork node and teaser so we can get feedback/approval on design and to help us determine how we should structure this.

# Additional Info

Example node from current site https://www.facilities.uiowa.edu/art-on-campus/artwork/voyage

Media - Currently allows unlimited images and video but looks like every piece of artwork has one image and some have one video. The images don't all have the same aspect ratio. (e.g. https://www.facilities.uiowa.edu/art-on-campus/artwork/diapason, https://www.facilities.uiowa.edu/art-on-campus/artwork/2-3-1-1). Teaser images all render the same size currently.

# Proposed Solution

**Comment by bspeare** [comment] 2023-10-27 17:18
I have put together a couple of full node mockups at:

## Widescreen
- https://sandbox.prod.drupal.uiowa.edu/brain-mirror - image cropped at widescreen, click to view full image. 
- https://sandbox.prod.drupal.uiowa.edu/brain-mirror-alt - image cropped at widescreen, click to view full image. 

## No crop
- https://sandbox.prod.drupal.uiowa.edu/brain-mirror-alt-copy - image no crop, click to view full image. 
- https://sandbox.prod.drupal.uiowa.edu/diapason - image no crop, click to view full image.

**Comment by briand44** [comment] 2023-10-27 17:25
Looks good! How would it work with a vertical image like https://www.facilities.uiowa.edu/art-on-campus/artwork/diapason?

**Comment by briand44** [comment] 2023-10-27 17:27
Also, how are we representing the link to the artists website, if one exists?

**Comment by bspeare** [comment] 2023-10-27 17:36
@briand44 added the artist website link.    For vertical photos, I like the idea of cropping it widescreen no matter what with the lightbox pop-up showing the real aspect ratio.

**Comment by briand44** [comment] 2023-10-27 18:04
Thanks, I didn't notice the lightbox pop-up originally.

**Comment by bspeare** [comment] 2023-10-27 18:45
@briand44 I added a hover icon on the image to make it more apparent.  I couldn't get the ["search"](https://fontawesome.com/v5/icons/search?f=classic&s=solid) or ["expand"](https://fontawesome.com/v5/icons/expand?f=classic&s=solid) so I went with hand pointer for now.

**Comment by bspeare** [comment] 2023-10-27 19:00
For teaser, maybe just card stacked with widescreen crop, card title, subtitle, and badge?

<img width="530" alt="Screenshot 2023-10-27 at 1 59 23 PM" src="https://github.com/uiowa/uiowa/assets/1036433/281550de-04ce-41f7-942f-dab3c0620095">

**Comment by pyrello** [comment] 2023-10-27 21:03
> Looks good! How would it work with a vertical image like https://www.facilities.uiowa.edu/art-on-campus/artwork/diapason?

> @briand44 added the artist website link. For vertical photos, I like the idea of cropping it widescreen no matter what with the lightbox pop-up showing the real aspect ratio.

I don't love the idea of cropping a vertical image into widescreen format just because that can really ruin the experience of some pieces of art. Ideally we would be able to accommodate two different layouts depending on the type of artwork. Would be a great use for https://github.com/uiowa/uiowa/pull/4155.

**Comment by joewhitsitt** [comment] 2023-10-30 17:00
Because of the issues raised with vertical oriented images, I like the no-crop versions that was added to https://github.com/uiowa/uiowa/issues/7042#issuecomment-1783254654. This would keep the complexity lower for content that Ben mentioned [doesn't get a lot of traffic](https://github.com/uiowa/uiowa/issues/7020#issuecomment-1773131542).

**Comment by briand44** [comment] 2023-10-30 19:03
Initial Feedback from Facilities. They are concerned about not having high res images and they said the prefer https://sandbox.prod.drupal.uiowa.edu/brain-mirror-alt-copy the most. They seemed ok with having to click to see the full image even for the vertical images. They also mentioned having the video in the sidebar under the link to the map.

They want to share with the person who adds the artwork to get feedback.

**Comment by pyrello** [comment] 2023-10-31 14:28
> For teaser, maybe just card stacked with widescreen crop, card title, subtitle, and badge?
> 
> <img alt="Screenshot 2023-10-27 at 1 59 23 PM" width="530" src="https://user-images.githubusercontent.com/1036433/278735225-281550de-04ce-41f7-942f-dab3c0620095.png">

I think we should use the square crop for these so that the experience is similar for vertically- and horizontally-oriented images.

**Comment by bspeare** [comment] 2023-11-03 19:35
I updated https://sandbox.prod.drupal.uiowa.edu/diapason-cropped to move the video to the sidebar.  I put the map link below the description so that it wouldn't be so closely associated with the video.  Since, they do have a lot of low-resolution vertical images of artwork in their collection, maybe we move forward with the "no crop" layout and encourage them to get new images of the artwork with a `16/9` aspect ratio?

**Comment by briand44** [comment] 2023-11-03 20:40
or we could just implement it based on their feedback :smirk:

**Comment by pyrello** [comment] 2023-11-03 20:47
> or we could just implement it based on their feedback 😏

The problem is that we showed them a mockup that was curated to look the best. They did not actually see what images that are taller than wide would look like cropped. It's easy for them to say that they don't care about the cropping. I think it would be worth showing them what it might look like in the worst case.

**Comment by briand44** [comment] 2023-11-03 20:54
>The problem is that we showed them a mockup that was curated to look the best. They did not actually see what images that are taller than wide would look like cropped. It's easy for them to say that they don't care about the cropping. Let's show them some examples of what it would look like in the worst case.

I agree, an example of a vertical image cropped would be good.

Their current gallery shows all of the images at the same size using a wide aspect ratio. https://www.facilities.uiowa.edu/campus-spaces/art-campus/art-campus-gallery

**Comment by bspeare** [comment] 2023-11-03 21:02
It looks like their current site uses focal point module to make sure images like this aren't cropped below the head:
<img width="513" alt="Screenshot 2023-11-03 at 4 02 47 PM" src="https://github.com/uiowa/uiowa/assets/1036433/d3e5c241-8f98-4a49-a6c5-7212e88d4737">

<img width="321" alt="Screenshot 2023-11-03 at 4 01 58 PM" src="https://github.com/uiowa/uiowa/assets/1036433/16912cd5-d94f-437b-a714-fa13a09862d3">

**Comment by bspeare** [comment] 2023-11-14 15:19
Closing this as the customer has approved the mockup.

**Closed as completed by bspeare** 2023-11-14 15:19 UTC
Labels: story, facilities.uiowa.edu, medium
