### ISSUE TITLE
Allow non-admins to update entities authored by a blocked user

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#4760] opened 2022-02-04 14:38 UTC
# Problem
It is not possible to update entities authored by a blocked user: https://www.drupal.org/project/drupal/issues/2756271#comment-13787110 

# Steps to reproduce
Block a user. Masquerade as a webmaster. Try to edit content or media authored by blocked user.

# Proposed solution
TBD

**Comment by joewhitsitt** [comment] 2022-02-04 14:42
Workaround: change author to active user during edit

**Comment by joewhitsitt** [comment] 2024-03-26 20:43
Can't reproduce using the webmaster role.

I believe the other workaround is to re-assign to an active author before save if it isn't allowed which is in a way good content maintenance for the majority of situations. The default content types and event all allow the webmaster role to override the authored by field. Any issue with this would be feature or site specific. Closing.

**Closed as completed by joewhitsitt** 2024-03-26 20:43 UTC
Labels: enhancement
