### ISSUE TITLE
Digital Viewbook for College of Law

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3289] opened 2021-03-30 13:36 UTC
# Story

As a prospective law student evaluating law schools, I can view a digital viewbook for Iowa Law that helps me understand why Iowa might be the right choice for me.

Campaign is launching in August.

# Domain

- [x] Request from hostmaster CNAME viewbook.law.uiowa.edu pointed at at uiowa.github.io. 
- [x] Add a CNAME file like https://github.com/uiowa/uids/blob/main/CNAME

# Content outline

- [x]  Brand bar with Site Name "College of Law"
- [x] Welcome banner with text copy - _dummy text added_
- [x] CTA buttons with "Apply, Visit, Contact, Request Info" links - _developer guess at links. needs finalization_
- [x] Horizontal stats section with 4 stats - _need law specific stats_
- [x] 5 sections of `grid-panel` image/headline/copy alternating left / right alignment - _need content_
- [x] 3 student profiles using proposed solution listed below - _need content_
  - Card classes `card--stacked media--border card--enclosed bg--white card--centered-left card--alignment-left`
  - Media classes`card__media--medium card__media media--circle card__media`
  - Headline `h3 headline headline--uppercase`

# Proposed solution

- [x] Create law-viewbook repo using VueJS Site template https://github.com/uiowa/vuejs-site-template. 
- [x] Request domain viewbook.law.uiowa.edu
- [x] Set up page structure using components outlined above
- [x] Add card component to use for profiles (https://github.com/uiowa/admissions-viewbook/blob/main/src/components/Card.vue)?  It could follow the style modifications used on https://admissions.prod.drupal.uiowa.edu/student-profiles and look something like the screenshot below (using the card template).
- [x] Set up side navigation to sections
  - SUCCESS BY THE NUMBERS
    - Stats section
  - WHY CHOOSE IOWA LAW?
    - Grid panel secton
  - WHAT ARE HAWKEYES SAYING?
    - Profiles section
- [x] Get build to work.

![LAW-JDViewbook-2021-R1-2](https://user-images.githubusercontent.com/1036433/122116247-0338e100-cdeb-11eb-883e-8cde40b0bf2b.png)

**Comment by briand44** [comment] 2021-06-15 18:24
Need to figure out what domain they want

**Comment by briand44** [comment] 2021-06-15 18:25
Want to list a few student profiles so there may be additional work needed here

**Comment by bspeare** [comment] 2021-06-15 18:43
Confirmed: they want https://viewbook.law.uiowa.edu/ as the domain.

**Comment by joewhitsitt** [comment] 2021-06-22 16:00
Started https://github.com/uiowa/viewbook-law/pull/1

- Not sure how to get the build working. The readme for the template seems out of date.
- Looks like some style adjustments will need to be made as part of this work.
- We need copy from the customer before this can be consider done.

**Comment by joewhitsitt** [comment] 2021-06-22 21:57
I am out tomorrow, 6/23 so I am hoping this can be picked up by others. @GaryRidgway helped me get the build working and started to help refactor the card component from the Admissions viewbook. A lot of variables and such have changed this it was first put together.

Work is currently happening on https://github.com/uiowa/viewbook-law/pull/1 now that we have the build process working.

Ultimately, this needs content.

**Comment by bspeare** [comment] 2021-06-24 13:19
I think https://github.com/uiowa/viewbook-law/pull/1 is ready for review and we could create a follow-up issue once we get content.

**Comment by bspeare** [comment] 2021-06-24 20:06
Closing this and we can create a new issue once we get the content.

**Closed as completed by bspeare** 2021-06-24 20:06 UTC
Labels: story, mobbing wanted
