### ISSUE TITLE
Update Photoswipe grouping patch in order to update Photoswipe to `3.1.4`

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5332] opened 2022-06-02 16:52 UTC
# Problem

I'm trying to use Photoswipe on the residence hall content type for an image within a paragraph and I'm getting this error:
https://www.drupal.org/project/photoswipe/issues/3225905, it is fixed in `3.1.4`

We are currently stuck using `3.1.1` version of Photoswipe because of these two patches:

```
         "drupal/photoswipe": {
                "grouping": "https://www.drupal.org/files/issues/2022-02-07/photoswipe-gallery-group-2625985-28.patch",
                "Way to make lazyload work with photoswipe": "https://www.drupal.org/files/issues/2022-02-09/support_lazy_module-3115456-9.patch"
            },
```

One issue is in progress:

https://www.drupal.org/project/photoswipe/issues/2625984

The other is closed, wont fix:

https://www.drupal.org/project/photoswipe/issues/3115456

# Proposed solution

- Update patch for https://www.drupal.org/project/photoswipe/issues/2625984.

**Comment by joewhitsitt** [comment] 2022-06-06 21:22
I think we can get away with removing https://www.drupal.org/project/photoswipe/issues/3115456

Like the maintainer says, the browser supported lazy attribute is present and seems to work, though it won't have the same lazy effect as the lazy module.

<img width="933" alt="Screen Shot 2022-06-06 at 4 21 30 PM" src="https://user-images.githubusercontent.com/4663676/172251384-b55a5cd0-4185-4bd5-bb0d-a0643e49e3ca.png">

The grouping one we need to keep. Ideally we would get the MR working again with the dev version so we can update

**Comment by joewhitsitt** [comment] 2022-06-08 21:38
@bspeare when you get a chance could i get a list of steps to reproduce? on the residence hall content type photoswipe is configured for the images field. it isn't in a paragraph.

**Comment by bspeare** [comment] 2022-06-09 13:26
@joewhitsitt go to https://housing.uiowa.ddev.site/admin/structure/paragraphs_type/housing_floor_plan/display and switch the image field to use Photoswipe.

**Comment by joewhitsitt** [comment] 2022-08-02 20:25
I poked at this a bit and realized that we might not need this "grouping" patch after all. We are hardcoding photoswipe-gallery in the template instead of using this functionality. Oops.

<img width="562" alt="Screen Shot 2022-08-02 at 3 24 59 PM" src="https://user-images.githubusercontent.com/4663676/182466744-9b8f86ff-0522-4bbc-a6ad-9e01cac67a4c.png">

**Comment by bspeare** [comment] 2022-08-02 20:29
@joewhitsitt nice find! :)

**Comment by joewhitsitt** [comment] 2022-08-02 21:04
However, I think this should wait till #5389 because the browser loading="lazy" was added in 9.4 which is the other patch that is keeping us from upgrading.

The update hook associated with the update will require configuration updates/exports for default image gallery view mode, housing res hall, uipress book and any others between now and then.

**Comment by joewhitsitt** [comment] 2022-12-15 16:05
lazy in 9.4 isn't enough due to responsive image.

https://github.com/uiowa/uiowa/issues/5121#issuecomment-1353323614

**Comment by joewhitsitt** [comment] 2023-09-27 20:32
We might have to go straight to 10.1 to do get photoswipe to d10 compatible and to maintain responsive image lazy loading

https://www.drupal.org/node/3279032

**Comment by joewhitsitt** [comment] 2023-10-23 15:04
I think we can close this in favor of the remaining slice https://github.com/uiowa/uiowa/issues/6965

**Closed as completed by joewhitsitt** 2023-10-23 15:04 UTC
Labels: bug, dependencies
