### ISSUE TITLE
Breadcrumbs block will not display within page_title_hero block

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1173] opened 2020-03-11 21:36 UTC
# Problem 

Using the twig_tweak code listed here: https://github.com/uiowa/uiowa/blob/0f6e9a0fbef15f07d9b62d22b90536502f78aae2/docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-page-title-hero.html.twig#L40, the breadcrumbs block will not display within the page_title_hero block.   

When "hidden when layout builder is active" is unchecked in the Layout Builder Active tab in the block setting, then it will output the proper breadcrumbs.  

# Proposed solution

Can we change the config for the Layout Builder Active tab?

**Comment by bspeare** [comment] 2020-03-13 14:15
Possibly related to #1037

**Comment by pyrello** [comment] 2020-03-13 16:47
Ugh... so, this solution is not working because when the block is not directly embedded via layout builder, it seems to be evaluating the condition plugin and therefore not showing.

I also tried enabling layout builder on the block type and adding the breadcrumb that way, but the same problem seems to be in effect.

**Comment by bspeare** [comment] 2020-03-13 16:59
I don't see duplicate breadcrumbs displayed if 'Hidden when Layout Builder is active' is unchecked.  Is that what that functionality is there to prevent?

**Comment by pyrello** [comment] 2020-03-13 18:05
I'm completely lost in this issue. The condition plugin seems to work fine, and predictably with the page title block, but not with the breadcrumbs. I tried to disable the layout_builder_custom module entirely, which causes the page title to show up twice, but the breadcrumbs do not. I'm not sure what other mechanism is at work here.

I am fine with turning off that setting for the breadcrumbs block for now to see if that introduces any unexpected behavior. We may have to revisit this issue.

**Comment by bspeare** [comment] 2020-03-13 18:18
Sure, let's see how far we can get with 'Hidden when Layout Builder is active' unchecked.  Is that set in the module or in config?

**Comment by pyrello** [comment] 2020-03-16 13:58
Closing this for now.

**Closed as completed by pyrello** 2020-03-16 13:58 UTC
Labels: uids_base, uiowa.edu
