### ISSUE TITLE
Fix Broken Remove image button in LB

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#960] opened 2019-11-18 22:58 UTC
Create a new block that contains an image and add the image to the block. After the image has been added, you will see a small thumbnail of the image with the "Remove image" button shortened to "Rem" and overlaying the thumbnail. See image below:
![Screen Shot 2019-11-18 at 3 27 00 PM](https://user-images.githubusercontent.com/3067017/69101212-a1ed3800-0a24-11ea-8046-c409794c0585.png)

**Comment by richardbporter** [comment] 2020-07-14 21:25
Do we still want to widen the tray a bit? Thats one of the first things I noticed when playing around with LB is that it seems too narrow most of the time.

**Comment by bspeare** [comment] 2020-07-14 21:35
I think we do!

**Comment by richardbporter** [comment] 2020-07-14 21:36
Thanks. I can take a shot at this as part of the research spike.

**Comment by bspeare** [comment] 2020-07-14 21:38
https://www.drupal.org/project/lb_claro has a nice tray width to check out.

**Comment by bspeare** [comment] 2020-07-14 21:48
@richardbporter You can check out https://github.com/uiowa/uiowa/issues/1366#issuecomment-658430504 for more tray discussion.

**Comment by richardbporter** [comment] 2020-07-17 19:01
~~Do we still want to use lb_claro and/or lb_ux or just take ideas from them?~~

Nevermind.

**Comment by richardbporter** [comment] 2020-07-17 19:20
Is the original issue still happening? What block type was used? It looks ok to me on blocks with an image field.
![image](https://user-images.githubusercontent.com/1068523/87823315-ad556500-c838-11ea-9288-e6bcfe437984.png)

**Comment by richardbporter** [comment] 2020-07-17 19:51
I can't reproduce this. I don't know if something changed with the media widget used in LB blocks but maybe we should close this and do the tray UX improvements in #1366 . 

Feel free to reopen if this still a problem.

**Closed as completed by richardbporter** 2020-07-17 19:51 UTC
Labels: layout builder, needs more info
