### ISSUE TITLE
Filtering at the top of person page

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3043] opened 2021-02-09 20:25 UTC
## Story

As a site owner, I can opt-in to views filtering on the SiteNow People view page.

## Proposed Solution

- [x] Locally establish all the filtering that should be made available on the "Default" Master display. Do not expose the filters.
  - [x] Name, Title or Position (first name/last name, title/position contains) - filter query name = `search`
  - [x] Person Type (preferably a dropdown of available options) - filter query name = `type`
  - [x] Research Areas autocomplete - filter query name = `research`
- [x] Provide reset button (shouldn't show unless filters are exposed)
- [x] Save the config so that it is setup but not exposed for new sites (you need to temporarily remove the view from config ignore to export)
- [x] Convert that exported yml diff to an update hook as this view is ignored and custom to every website. Assumes, the update hook will only touch the filters portion of config and that no sites have added their own filter.
- [x] Add booleans to the SiteNow People configuration form to toggle the exposure of these filters. View #2526 for additional details on setting this up.

**Comment by pyrello** [comment] 2021-02-09 20:34
Duplicate of #2524

**Comment by joewhitsitt** [comment] 2021-02-10 14:32
This could be related to the issue I was having with the configuration entity dropdown for person types: https://www.drupal.org/node/2429699

**Comment by pyrello** [comment] 2021-02-10 15:08
Do we want to tackle all of these filters in one go? It sounded like the most critical one is the person type filter.

**Comment by joewhitsitt** [comment] 2021-02-10 16:08
It should be fairly easy to add name, position. I like the idea that the site owner can choose which ones they want in the end

**Comment by pyrello** [comment] 2021-02-15 04:03
This article may provide a way forward if the related issue doesn't: https://atendesigngroup.com/articles/drupal-8-views-entity-reference-exposed-filter-select-list

Another alternative option: https://www.drupal.org/project/entityreference_filter

**Comment by joewhitsitt** [comment] 2021-03-10 21:35
The latest core patch appears to work and works similar to the reference field itself where you can filter bundles, provide entity reference view for filtering:
https://github.com/uiowa/uiowa/issues/3043#issuecomment-776747593

**Comment by joewhitsitt** [comment] 2021-03-23 15:51
Patch was applied to https://github.com/uiowa/uiowa/pull/3249 so this should be ready to work with.

**Comment by joewhitsitt** [comment] 2021-03-24 17:50
The patch to allow entity reference filtering https://github.com/uiowa/uiowa/issues/3043#issuecomment-776747593 doesn't work as I thought it did so I moved forward with https://github.com/uiowa/uiowa/issues/3043#issuecomment-778922375 and committed https://github.com/uiowa/uiowa/pull/3269/commits/69f03a199be112de0d832d34118f9b7ef6f58667

@GaryRidgway  ran into the issue that combine filter needs the fields on the view and that the title/position isn't able to be added because it is multi value. Apparently this is working as designed: https://www.drupal.org/project/drupal/issues/2945744

To move this forward for now, we can still use the combine filter with the title field and establish that as an MVP that can be extended later. Following up we can create an access none long text field on the person content type that would populate on save with the position/title values and anything else we want to throw in there to search (filter) on.

It still complicates things because we will need to expand the update hook to change from content render to fields (rendered entity, title, hidden long text) not only for the master display but for the manual sort display as that has forked when it comes to the view row render.

**Closed as completed** 2021-03-31 20:36 UTC
